#!/bin/sh

CONFIG=~/.screen-sharing.config

if [ ! -e $CONFIG ]; then
  echo "In ${CONFIG}, put the contents \"PROXY=<address to proxy host>\""
  exit 1
fi

. $CONFIG

LOCAL_PORT=5959
REMOTE_PORT=5900

ssh $PROXY -L ${LOCAL_PORT}:localhost:${REMOTE_PORT} -N &
pid=$!

sleep 2
open vnc://localhost:5959/

echo "Press enter to close the SSH tunnel"
read
kill $pid
