#!/bin/sh

CONFIG=~/.screen-sharing.config

if [ ! -e $CONFIG ]; then
  echo "In ${CONFIG}, put the contents \"PROXY=<address to proxy host>\" and also set VNC_SERVER_PORT to the port for the VNC server unless it's the default 5900"
  exit 1
fi

. $CONFIG

if [ "${VNC_SERVER_PORT}" = "" ]; then
   VNC_SERVER_PORT=5900
fi
HOSTPORT=5900

ssh $PROXY -R ${VNC_SERVER_PORT}:localhost:${HOSTPORT} -N &
